/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations, Html,Text, Text3D } from "@react-three/drei";
import * as THREE from 'three'
import url from "/src/assets/osito2.mp4"
import url2 from "/src/assets/Nadador.mp4"
import { useDispatch, useSelector } from "react-redux";
import { chCam, chTravel, chCam2,chTravel2,chBuzon,chBuzon2, chLoading } from "../Slice/Theme";
import { extend, useFrame } from "@react-three/fiber";
//import { Text } from "troika-three-text";
import fonst from "../assets/fonst";
import AboutPage from "./AboutPage";
import Proyects from "./Proyects";
import Loader from "./Loader";




const text ="About Me";
  
const glowRed = new THREE.MeshBasicMaterial({ color: new THREE.Color("#FAF9CF"), toneMapped: false })
const glowBuesCar = new THREE.MeshBasicMaterial({ color: new THREE.Color("#50C9E7"), toneMapped: false })
const glowPurpue = new THREE.MeshBasicMaterial({ color: new THREE.Color("#D347E7"), toneMapped: false })
const glowBlue = new THREE.MeshBasicMaterial({ color: new THREE.Color(0, 0.5, 20), toneMapped: false })
const glowGreen = new THREE.MeshBasicMaterial({ color: new THREE.Color("#6CE76F"), toneMapped: false })
const glowYellow = new THREE.MeshBasicMaterial({ color: new THREE.Color("#E7092D"), toneMapped: false })
const glowRedyell = new THREE.MeshBasicMaterial({ color: new THREE.Color("#FDDE0A"), toneMapped: false })


export function Home(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/casaPort27.glb");
  const { actions } = useAnimations(animations, group);
  const dispatch=useDispatch()
  const [hovered, setHovered] = useState(false)
  const [color, setColor] = useState("white")
  
 
  const abaout=useSelector((state=>state.counter.travel))
  const proyect=useSelector((state=>state.counter.cam))
  const buzon=useSelector((state=>state.counter.buzon))
  const loading=useSelector((state=>state.counter.loading))
  const mobile=useSelector((state=>state.counter.mobile))
  
  useFrame((state) => {
    // if(rot){
       const t = state.clock.getElapsedTime()
       document.body.style.cursor = hovered ? 'pointer' : 'auto'
      
   })
  
  useEffect(()=>{
    
    //console.log("los actions son",actions)
    /* if(mobile===false){
    actions.AbuelaAction.play()
    actions.M_CalcaAction.play()
    actions.CreidaAction.play()
    actions.venti_2Action.play()
    actions.girtoAntenaAction.play()
    actions.M_Action2.play()
    actions.CafeAction2.play()
    actions.Hazul_Action2.play()}
    else{
      console.log("mobile active")
    } */
  })

  const [video]= useState(()=>{
    const vid =document.createElement("video");
    vid.src= url;
    vid.crossOrigin="Anonymous";
    vid.loop=true;
    vid.muted=true;
    vid.play();
    return vid;


  })
  const [video2]= useState(()=>{
    const vid =document.createElement("video");
    vid.src= url2;
    vid.crossOrigin="Anonymous";
    vid.loop=true;
    vid.muted=true;
    vid.play();
    return vid;


  })


  const VideoTextures=new THREE.VideoTexture(video);
  VideoTextures.minFilter=THREE.NearestFilter
  VideoTextures.magFilter = THREE.NearestFilter;
  VideoTextures.encoding = THREE.sRGBEncoding;

  const VideoTextures2=new THREE.VideoTexture(video2);
  VideoTextures2.minFilter=THREE.NearestFilter
  VideoTextures2.magFilter = THREE.NearestFilter;
  VideoTextures2.encoding = THREE.sRGBEncoding;

  useEffect(()=>{
    dispatch(chLoading())
    
    //console.log("cargado")    
  },[])

  
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Trash_Can"
          position={[8.004171, 0.294273, -0.356716]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.003329}
        />
        <group
          name="Bosque"
          position={[8.004295, 0.435282, -0.357113]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.003329}
        >
          <group
            name="Lid001"
            position={[302.990479, -182.540695, 114.880302]}
            rotation={[0, -0.851371, 0]}
          >
            <mesh
              name="Mesh069"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069.geometry}
              material={materials["TAPA BASURA"]}
            />
            <mesh
              name="Mesh069_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_1.geometry}
              material={materials["Material.026"]}
            />
            <mesh
              name="Mesh069_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_2.geometry}
              material={materials["Material.024"]}
            />
            <mesh
              name="Mesh069_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_3.geometry}
              material={materials["Material.025"]}
            />
            <mesh
              name="Mesh069_4"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_4.geometry}
              material={materials["Material.027"]}
            />
            <mesh
              name="Mesh069_5"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_5.geometry}
              material={materials["leaf_green.002"]}
            />
            <mesh
              name="Mesh069_6"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_6.geometry}
              material={materials["leaf_green.005"]}
            />
            <mesh
              name="Mesh069_7"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_7.geometry}
              material={materials.leaf_green}
            />
            <mesh
              name="Mesh069_8"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_8.geometry}
              material={materials["leaf_green.001"]}
            />
            <mesh
              name="Mesh069_9"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_9.geometry}
              material={materials["leaf_green.004"]}
            />
            <mesh
              name="Mesh069_10"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_10.geometry}
              material={materials["leaf_green.003"]}
            />
            <mesh
              name="Mesh069_11"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_11.geometry}
              material={materials.tree_wood}
            />
            <mesh
              name="Mesh069_12"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_12.geometry}
              material={materials.lambert18}
            />
            <mesh
              name="Mesh069_13"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_13.geometry}
              material={materials.DefaultMaterial}
            />
            <mesh
              name="Mesh069_14"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_14.geometry}
              material={materials["DefaultMaterial.001"]}
            />
            <mesh
              name="Mesh069_15"
              castShadow
              receiveShadow
              geometry={nodes.Mesh069_15.geometry}
              material={materials.BASURA}
            />
          </group>
        </group>
        
        <mesh
          name="CAble"
          castShadow
          receiveShadow
          geometry={nodes.CAble.geometry}
          material={materials.CABLES}
          position={[0.477803, 10.734864, -3.052925]}
        />
        <mesh
          name="cable3"
          castShadow
          receiveShadow
          geometry={nodes.cable3.geometry}
          material={materials.CABLES}
          position={[-1.129382, 10.074607, -4.243993]}
        />
        <group
          name="H_cafe"
          position={[6.84454775, 0.91401076, 4.37037706]}
          rotation={[-Math.PI / 2, 1.5e-7, -1.99400771]}
          scale={0.01}
        >
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            name="Object_101"
            geometry={nodes.Object_101.geometry}
            material={materials["peopleColorsFam.002"]}
            skeleton={nodes.Object_101.skeleton}
          />
        </group>
        <group
          name="M_azul"
          position={[6.10937738, 0.86468846, 5.49291372]}
          rotation={[-Math.PI / 2, -1.9e-7, 1.40546279]}
          scale={0.01}
        >
          <primitive object={nodes._rootJoint_1} />
          <skinnedMesh
            name="Object_145"
            geometry={nodes.Object_145.geometry}
            material={materials["peopleColors.001"]}
            skeleton={nodes.Object_145.skeleton}
          />
        </group>
        <group
          name="M_Calca"
          position={[-4.04662895, 7.18243361, -0.71370804]}
          rotation={[-Math.PI / 2, 3.8e-7, -1.39231718]}
          scale={0.01}
        >
          <primitive object={nodes._rootJoint_3} />
          <skinnedMesh
            name="Object_53002"
            geometry={nodes.Object_53002.geometry}
            material={materials["peopleColorsFam.007"]}
            skeleton={nodes.Object_53002.skeleton}
          />
          <skinnedMesh
            name="Object_94002"
            geometry={nodes.Object_94002.geometry}
            material={materials["peopleColorsFam.007"]}
            skeleton={nodes.Object_94002.skeleton}
          />
        </group>
        <group
          name="M_vieja"
          position={[0.69117844, 3.62434387, 0.84609836]}
          rotation={[-Math.PI / 2, -2e-8, 0.74354185]}
          scale={0.01}
        >
          <primitive object={nodes._rootJoint_4} />
          <skinnedMesh
            name="Object_9001"
            geometry={nodes.Object_9001.geometry}
            material={materials["peopleColorsFam.008"]}
            skeleton={nodes.Object_9001.skeleton}
          />
        </group>
        <group
          name="Abuela"
          position={[1.94502711, 4.06251431, -0.52388704]}
          rotation={[-Math.PI / 2, 8e-8, -1.85939951]}
          scale={0.01}
        >
          <primitive object={nodes._rootJoint_5} />
          <skinnedMesh
            name="Object_246"
            geometry={nodes.Object_246.geometry}
            material={materials["peopleColors.002"]}
            skeleton={nodes.Object_246.skeleton}
          />
          <skinnedMesh
            name="Object_290"
            geometry={nodes.Object_290.geometry}
            material={materials["peopleColors.002"]}
            skeleton={nodes.Object_290.skeleton}
          />
        </group>
        <group
          name="medico"
          position={[-1.73173475, 7.18764353, 0.36745226]}
          rotation={[-Math.PI / 2, -2.2e-7, 2.2675979]}
          scale={[0.01000001, 0.01, 0.01]}
        >
          <primitive object={nodes._rootJoint_2} />
          <skinnedMesh
            name="Object_193"
            geometry={nodes.Object_193.geometry}
            material={materials["peopleColors.005"]}
            skeleton={nodes.Object_193.skeleton}
          />
        </group>
        <mesh
          name="calbe2"
          castShadow
          receiveShadow
          geometry={nodes.calbe2.geometry}
          material={materials.CABLES}
          position={[0.41152, 10.711896, -3.052926]}
        />
        <mesh
          name="calble"
          castShadow
          receiveShadow
          geometry={nodes.calble.geometry}
          material={nodes.calble.material}
          position={[-1.779163, 9.451241, -5.249079]}
        />
        <mesh
          name="cable4"
          castShadow
          receiveShadow
          geometry={nodes.cable4.geometry}
          material={materials.CABLES}
          position={[-2.864102, 9.898415, -4.936801]}
        />
        <mesh
          name="entrada_pareuq"
          castShadow
          receiveShadow
          geometry={nodes.entrada_pareuq.geometry}
          material={materials.marmol}
          position={[-2.307118, 1.342484, 3.859451]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={1.152728}
        />
        <group
          name="rejas_piso_1"
          position={[2.14263, 0.264939, -2.278699]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[-0.036529, -0.035244, -0.035244]}
        >
          <mesh
            name="Cube023"
            castShadow
            receiveShadow
            geometry={nodes.Cube023.geometry}
            material={materials.REJAS}
          />
          <mesh
            name="Cube023_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube023_1.geometry}
            material={materials.ventanas_trasparente}
          />
        </group>
        <group
          name="edificio"
          position={[-3.9907, 3.048515, 3.904173]}
          scale={1.986225}
        >
          <mesh
            name="Plane002"
            castShadow
            receiveShadow
            geometry={nodes.Plane002.geometry}
            material={materials.marmol}
            
          />
          <mesh
            name="Plane002_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane002_1.geometry}
            material={materials.piso}
          />
          <mesh
            name="Plane002_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane002_2.geometry}
            material={materials.pared}
          />
          <mesh
            name="Plane002_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane002_3.geometry}
            material={glowRed}
          />
          <mesh
            name="Plane002_4"
            castShadow
            receiveShadow
            geometry={nodes.Plane002_4.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Plane002_5"
            castShadow
            receiveShadow
            geometry={nodes.Plane002_5.geometry}
            material={materials.VENTANA}
          />
          <mesh
            name="Plane002_6"
            castShadow
            receiveShadow
            geometry={nodes.Plane002_6.geometry}
            material={materials["Material.019"]}
          />
        </group>
        
        <group
          name="base_ventilado_2"
          position={[1.497852, 9.862914, -5.370657]}
          scale={0.521022}
        >
          <mesh
            name="Plane005"
            castShadow
            receiveShadow
            geometry={nodes.Plane005.geometry}
            material={materials.ventiladoe2}
          />
          <mesh
            name="Plane005_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane005_1.geometry}
            material={materials.ventiladoe2}
          />
        </group>
        <group
          name="rejas_piso_2"
          position={[2.14263, 3.217822, -2.278699]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[-0.036529, -0.035244, -0.035244]}
        >
          <mesh
            name="Cube022"
            castShadow
            receiveShadow
            geometry={nodes.Cube022.geometry}
            material={materials.REJAS}
          />
          <mesh
            name="Cube022_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube022_1.geometry}
            material={materials.ventanas_trasparente}
          />
        </group>
        <mesh
          name="venti_2"
          castShadow
          receiveShadow
          geometry={nodes.venti_2.geometry}
          material={materials.aspas}
          position={[1.497852, 9.783439, -5.370657]}
          rotation={[-Math.PI, 1.250891, -Math.PI]}
          scale={0.063876}
        />
        <group
          name="rejas_piso_3"
          position={[-5.52122, 6.358737, -2.278699]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[-0.036529, -0.035244, -0.035244]}
        >
          <mesh
            name="Cube026"
            castShadow
            receiveShadow
            geometry={nodes.Cube026.geometry}
            material={materials.REJAS}
          />
          <mesh
            name="Cube026_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube026_1.geometry}
            material={materials.ventanas_trasparente}
          />
        </group>
        <mesh
          name="ventilador"
          castShadow
          receiveShadow
          geometry={nodes.ventilador.geometry}
          material={materials["piso ventilador"]}
          position={[1.497852, 9.758862, -5.370657]}
          scale={0.339929}
        />
        <mesh
          name="sup_venti_2"
          castShadow
          receiveShadow
          geometry={nodes.sup_venti_2.geometry}
          material={materials.ventilado}
          position={[1.497852, 9.865423, -5.370657]}
          scale={0.555269}
        />
        <group
          name="ventilado_1"
          position={[0.1413, 9.621524, -5.397768]}
          scale={[0.239347, 0.167749, 0.362467]}
        >
          <mesh
            name="Cube038"
            castShadow
            receiveShadow
            geometry={nodes.Cube038.geometry}
            material={materials.Material}
          />
          <mesh
            name="Cube038_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube038_1.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <mesh
          name="Ladrillos"
          castShadow
          receiveShadow
          geometry={nodes.Ladrillos.geometry}
          material={materials.marmol}
          position={[2.231698, 9.155363, -2.332386]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.192085, -0.071381, -0.065122]}
        />
        <group
          name="Obj_Chair002"
          position={[0.74071652, 3.14255023, 0.81674188]}
          rotation={[-Math.PI, 0.753487, -Math.PI]}
          scale={1.000251}
        >
          <mesh
            name="Cube060"
            castShadow
            receiveShadow
            geometry={nodes.Cube060.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            name="Cube060_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube060_1.geometry}
            material={materials.parasMesas}
          />
        </group>
        <group
          name="puerta_3"
          position={[-1.802016, 7.314202, -2.340736]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.572588, 1, 1]}
        >
          <mesh
            name="Plane007"
            castShadow
            receiveShadow
            geometry={nodes.Plane007.geometry}
            material={materials.puerta}
          />
          <mesh
            name="Plane007_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane007_1.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Plane007_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane007_2.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            name="Plane007_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane007_3.geometry}
            material={glowRed}
          />
        </group>
        <mesh
          name="cima_parasol"
          castShadow
          receiveShadow
          geometry={nodes.cima_parasol.geometry}
          material={nodes.cima_parasol.material}
          position={[-3.13795, 9.441238, -0.414881]}
          scale={0.055163}
        />
        <group
          name="puerta_2"
          position={[-1.704016, 4.164691, -1.3772]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.516835, 1, 0.998739]}
        >
          <mesh
            name="Plane001"
            castShadow
            receiveShadow
            geometry={nodes.Plane001.geometry}
            material={materials.puerta}
          />
          <mesh
            name="Plane001_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_1.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Plane001_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_2.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            name="Plane001_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_3.geometry}
            material={glowRed}
          />
        </group>
        <group
          name="puerta_entrada"
          position={[-5.843803, 1.10623, -0.133626]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.516835, 1, 0.912823]}
        >
          <mesh
            name="Plane009"
            castShadow
            receiveShadow
            geometry={nodes.Plane009.geometry}
            material={materials.puerta}
          />
          <mesh
            name="Plane009_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane009_1.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Plane009_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane009_2.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            name="Plane009_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane009_3.geometry}
            material={glowRed}
          />
        </group>
        <group
          name="puerta_1"
          position={[-1.688176, 1.095173, -1.3772]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.516835, 1, 0.899943]}
        >
          <mesh
            name="Plane008"
            castShadow
            receiveShadow
            geometry={nodes.Plane008.geometry}
            material={materials.puerta}
          />
          <mesh
            name="Plane008_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane008_1.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Plane008_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane008_2.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            name="Plane008_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane008_3.geometry}
            material={glowRed}
          />
        </group>
        <group
          name="entrada_cubierta"
          position={[-6.466391, 2.635919, -1.152949]}
          rotation={[0.009491, -0.299707, 3.134592]}
          scale={0.081482}
        >
          <mesh
            name="Cylinder010"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            name="Cylinder010_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_1.geometry}
            material={materials["Material.020"]}
          />
        </group>
        <mesh
          name="parasol"
          castShadow
          receiveShadow
          geometry={nodes.parasol.geometry}
          material={materials.PARASOL}
          position={[-3.137949, 9.488691, -0.41488]}
          rotation={[0, Math.PI / 2, 0]}
          scale={1.260211}
        />
        <mesh
          name="piso_parque"
          castShadow
          receiveShadow
          geometry={nodes.piso_parque.geometry}
          material={materials["PISO PARQUE"]}
          position={[-3.83179, 0.231886, 3.936718]}
          scale={[1.843807, 0.163551, 1.843807]}
        />
        <group
          name="planta_a001"
          position={[-1.446463, 0.278007, 5.312078]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.003798}
        >
          <mesh
            name="Mesh002"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh002_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <group
          name="MESA001"
          position={[1.09986711, 3.15566468, 0.30634779]}
          rotation={[-Math.PI, 0.753487, -Math.PI]}
          scale={[0.17731, 0.01248, 0.17731]}
        >
          <mesh
            name="Cylinder014"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder014.geometry}
            material={materials.BASE_MESA}
          />
          <mesh
            name="Cylinder014_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder014_1.geometry}
            material={materials.MESA}
          />
        </group>
        <group
          name="MESA"
          position={[-3.910585, 6.282998, -0.385784]}
          scale={[0.198639, 0.013981, 0.198639]}
        >
          <mesh
            name="Cylinder013"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder013.geometry}
            material={materials.BASE_MESA}
          />
          <mesh
            name="Cylinder013_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder013_1.geometry}
            material={materials.MESA}
          />
        </group>
        <group
          name="Obj_Chair005"
          position={[-4.008356, 6.268306, -1.078082]}
          scale={1.120576}
        >
          <mesh
            name="Cube045"
            castShadow
            receiveShadow
            geometry={nodes.Cube045.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            name="Cube045_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube045_1.geometry}
            material={materials.parasMesas}
          />
        </group>
        <group
          name="Obj_Chair003"
          position={[1.489483, 3.14255023, 0.01859373]}
          rotation={[0, -0.753486, 0]}
          scale={1.000251}
        >
          <mesh
            name="Cube061"
            castShadow
            receiveShadow
            geometry={nodes.Cube061.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            name="Cube061_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube061_1.geometry}
            material={materials.parasMesas}
          />
        </group>
        <group
          name="Obj_Chair001"
          position={[-4.008356, 6.268306, 0.147958]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={1.120576}
        >
          <mesh
            name="Cube046"
            castShadow
            receiveShadow
            geometry={nodes.Cube046.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            name="Cube046_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube046_1.geometry}
            material={materials.parasMesas}
          />
        </group>
        <group
          name="sillapark"
          position={[0.179131, 0.867403, -2.255337]}
          rotation={[-1.870288, Math.PI / 2, 0]}
          scale={[-0.09696, -0.019873, -0.917191]}
        >
          <mesh
            name="Cube071"
            castShadow
            receiveShadow
            geometry={nodes.Cube071.geometry}
            material={materials["silla park"]}
          />
          <mesh
            name="Cube071_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube071_1.geometry}
            material={materials.MESA}
          />
        </group>
        <group
          name="matera_grande"
          position={[1.650995, 0.45059, 0.171156]}
          scale={[0.223755, 0.245976, 0.798708]}
        >
          <mesh
            name="Cube081"
            castShadow
            receiveShadow
            geometry={nodes.Cube081.geometry}
            material={materials["BASE MATERA"]}
          />
          <mesh
            name="Cube081_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube081_1.geometry}
            material={materials.TIERRA}
          />
        </group>
        <group
          name="planta_a_g"
          position={[1.655129, 0.458604, 0.79751]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.003798}
        >
          <mesh
            name="Mesh003"
            castShadow
            receiveShadow
            geometry={nodes.Mesh003.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh003_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh003_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <group
          name="planta_a_g001"
          position={[1.655255, 0.440073, 0.208762]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.003798}
        >
          <mesh
            name="Mesh005"
            castShadow
            receiveShadow
            geometry={nodes.Mesh005.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh005_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh005_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <mesh
          name="limite_casa"
          castShadow
          receiveShadow
          geometry={nodes.limite_casa.geometry}
          material={materials.marmol}
          position={[4.259267, -0.006818, 1.047917]}
          scale={[0.208558, 0.190855, 1]}
        />
        <group
          name="ESTRCU_PARASOL"
          position={[-3.13795, 6.348848, -0.414881]}
          rotation={[-2.181269, 0.520522, 2.523616]}
          scale={[0.024209, 0.036633, 0.036374]}
        >
          <mesh
            name="Cube053"
            castShadow
            receiveShadow
            geometry={nodes.Cube053.geometry}
            material={materials.ES_PARASOL}
          />
          <mesh
            name="Cube053_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube053_1.geometry}
            material={materials["BASE PARASOL"]}
          />
        </group>
        <group
          name="planta_a"
          position={[-1.446463, 0.278007, 2.379195]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.003798}
        >
          <mesh
            name="Mesh001"
            castShadow
            receiveShadow
            geometry={nodes.Mesh001.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh001_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh001_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <group
          name="MATERA"
          position={[-1.451864, 0.188803, 2.38359]}
          scale={0.201498}
        >
          <mesh
            name="Cube076"
            castShadow
            receiveShadow
            geometry={nodes.Cube076.geometry}
            material={materials["BASE MATERA"]}
          />
          <mesh
            name="Cube076_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube076_1.geometry}
            material={materials.TIERRA}
          />
        </group>
        <group
          name="planta_ag"
          position={[1.655255, 0.430351, -0.388051]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.003798}
        >
          <mesh
            name="Mesh006"
            castShadow
            receiveShadow
            geometry={nodes.Mesh006.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh006_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh006_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <group
          name="matera_g"
          position={[0.535089, 6.518252, 1.307851]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.223755, 0.245976, 0.798708]}
        >
          <mesh
            name="Cube082"
            castShadow
            receiveShadow
            geometry={nodes.Cube082.geometry}
            material={materials["BASE MATERA"]}
          />
          <mesh
            name="Cube082_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube082_1.geometry}
            material={materials.TIERRA}
          />
        </group>
        <group
          name="MATERA001"
          position={[-1.451864, 0.188803, 5.316473]}
          scale={0.201498}
        >
          <mesh
            name="Cube080"
            castShadow
            receiveShadow
            geometry={nodes.Cube080.geometry}
            material={materials["BASE MATERA"]}
          />
          <mesh
            name="Cube080_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube080_1.geometry}
            material={materials.TIERRA}
          />
        </group>
        <group
          name="planta_ag003"
          position={[-2.635755, 6.526265, 1.303718]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.003798}
        >
          <mesh
            name="Mesh010"
            castShadow
            receiveShadow
            geometry={nodes.Mesh010.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh010_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh010_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <mesh
          name="pisopaeque"
          castShadow
          receiveShadow
          geometry={nodes.pisopaeque.geometry}
          material={materials["Material.035"]}
          position={[0, -0.126859, -1.161307]}
          scale={9.501088}
        />
        <group
          name="planta_a_g002"
          position={[1.161444, 6.526265, 1.303718]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.003798}
        >
          <mesh
            name="Mesh007"
            castShadow
            receiveShadow
            geometry={nodes.Mesh007.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh007_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh007_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <group
          name="planta_ag004"
          position={[-3.224503, 6.535766, 1.303591]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.003798}
        >
          <mesh
            name="Mesh011"
            castShadow
            receiveShadow
            geometry={nodes.Mesh011.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh011_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh011_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <group
          name="planta_ag005"
          position={[-3.821315, 6.542539, 1.303591]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.003798}
        >
          <mesh
            name="Mesh012"
            castShadow
            receiveShadow
            geometry={nodes.Mesh012.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh012_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh012_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <mesh
          name="escaleras001"
          castShadow
          receiveShadow
          geometry={nodes.escaleras001.geometry}
          material={materials.ESCALERAS}
          position={[-6.113248, 0.015381, -0.029968]}
          rotation={[0, 0, -Math.PI]}
          scale={[0.662997, 0.069627, 1.197169]}
        />
        <group
          name="planta_ag001"
          position={[0.572696, 6.535766, 1.303591]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.003798}
        >
          <mesh
            name="Mesh008"
            castShadow
            receiveShadow
            geometry={nodes.Mesh008.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh008_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh008_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <group
          name="planta_ag002"
          position={[-0.024117, 6.542539, 1.303591]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.003798}
        >
          <mesh
            name="Mesh009"
            castShadow
            receiveShadow
            geometry={nodes.Mesh009.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh009_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <mesh
          name="pCube212008"
          castShadow
          receiveShadow
          geometry={nodes.pCube212008.geometry}
          material={materials.lambert18}
          position={[-7.868985, -0.331924, 6.747897]}
          rotation={[1.667838, -0.054817, -0.360507]}
          scale={[0.012395, 0.012498, 0.020809]}
        />
        <group
          name="matera_g001"
          position={[-3.262109, 6.518252, 1.307851]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.223755, 0.245976, 0.798708]}
        >
          <mesh
            name="Cube083"
            castShadow
            receiveShadow
            geometry={nodes.Cube083.geometry}
            material={materials["BASE MATERA"]}
          />
          <mesh
            name="Cube083_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube083_1.geometry}
            material={materials.TIERRA}
          />
        </group>
        <group
          name="planta_a002"
          position={[-1.446463, 0.278007, 2.379195]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.003798}
        >
          <mesh
            name="Mesh013"
            castShadow
            receiveShadow
            geometry={nodes.Mesh013.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh013_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh013_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <group
          name="planta_a003"
          position={[-1.446463, 0.278007, 5.312078]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.003798}
        >
          <mesh
            name="Mesh014"
            castShadow
            receiveShadow
            geometry={nodes.Mesh014.geometry}
            material={materials.Mat}
          />
          <mesh
            name="Mesh014_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh014_1.geometry}
            material={materials["Mat.3"]}
          />
        </group>
        <group
          name="PANELES"
          position={[1.637878, 10.520434, -3.153024]}
          rotation={[Math.PI / 2, 0.911869, -Math.PI / 2]}
          scale={[0.030994, 0.104309, 0.030994]}
        >
          <mesh
            name="Cylinder003"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003.geometry}
            material={materials.PATAS_SOLARES}
          />
          <mesh
            name="Cylinder003_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_1.geometry}
            material={glowGreen}
          />
          <mesh
            name="Cylinder003_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_1.geometry}
            material={glowGreen}
            position={[0,10.3,0]}
            rotation={[Math.PI,0,0]}
          />
          
        </group>
        <group
          name="Spring003"
          position={[5.703304, 0.283898, 3.694696]}
          rotation={[1.771509, 0, Math.PI / 2]}
          scale={0.015127}
        >
          <mesh
            name="Circle010"
            castShadow
            receiveShadow
            geometry={nodes.Circle010.geometry}
            material={materials["Black.002"]}
          />
          <mesh
            name="Circle010_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle010_1.geometry}
            material={materials["Light_black.002"]}
          />
        </group>
        <group
          name="pantalla"
          position={[-0.717721, 11.293582, -2.704186]}
          scale={[1.264269, 0.860077, 0.16591]}
        >
          <mesh
            name="Cube001"
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={materials.cartel}
            material-color={"#81CAB5"}
          />
          <mesh
            name="Cube001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={new THREE.MeshBasicMaterial({color: 0x00000}) }
          >
            {
              abaout ?  <Html scale={0.03} rotation={[0, 0, 0]} position={[0, -0.5,2]} transform occlude>
              <div className="annotation4">
              <div className="BackAno" style={{ fontSize: '4.5em'}} onClick={()=>{dispatch(chTravel2())}}  onPointerOver={() => {setHovered(true)}}
              onPointerOut={() => setHovered(false)}>
                Back <span className="letter" style={{ fontSize: '1.5em', color: "#FFFFFF" }} ></span>
              </div>
                <AboutPage/>
              </div>
            </Html>: <></>
            }
         
          </mesh>
        </group>
        <mesh
       position={[-0.717721, 11.293582, -2.704186]}
        geometry={new THREE.PlaneGeometry(1,1)}
        scale={[2.4,1.6,1]}
        rotation={[0,0,0]}
        material={abaout ? new THREE.MeshBasicMaterial({color: 0x00000}) :new THREE.MeshBasicMaterial({
            map:  VideoTextures2
                    })  }
        ></mesh>
        <group
          name="Spring"
          position={[7.236587, 0.288906, 2.810123]}
          rotation={[1.35263, 0, -Math.PI / 2]}
          scale={0.015127}
        >
          <mesh
            name="Circle013"
            castShadow
            receiveShadow
            geometry={nodes.Circle013.geometry}
            material={materials["Black.002"]}
          />
          <mesh
            name="Circle013_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle013_1.geometry}
            material={materials["Light_black.002"]}
          />
        </group>
        <mesh
          name="base_antena"
          castShadow
          receiveShadow
          geometry={nodes.base_antena.geometry}
          material={materials.antena}
          position={[-3.676729, 10.620749, -4.335822]}
          scale={[0.347953, 0.095031, 0.347953]}
        />
        <mesh
          name="piso"
          castShadow
          receiveShadow
          geometry={nodes.piso.geometry}
          material={materials.pisp}
          position={[1.007096, -0.131407, 2.125313]}
          scale={[-0.253096, -0.127836, -0.50866]}
        />
        <mesh
          name="girto_antena"
          castShadow
          receiveShadow
          geometry={nodes.girto_antena.geometry}
          material={materials.antena}
          position={[-3.676729, 11.331065, -4.335822]}
          scale={0.137315}
        />
        <mesh
          name="entrada_cables"
          castShadow
          receiveShadow
          geometry={nodes.entrada_cables.geometry}
          material={materials["Material.021"]}
          position={[-0.746234, 11.270007, -2.894904]}
          scale={[0.136243, 0.136243, 0.041957]}
        />
        <mesh
          name="pCube212026"
          castShadow
          receiveShadow
          geometry={nodes.pCube212026.geometry}
          material={materials.lambert18}
          position={[4.965889, -0.331924, -9.169538]}
          rotation={[1.674471, 0.040867, 0.526299]}
          scale={[0.012395, 0.012498, 0.020809]}
        />
        <mesh
          name="lamrapa_calle"
          castShadow
          receiveShadow
          geometry={nodes.lamrapa_calle.geometry}
          material={glowBlue}
          position={[9.05, 3.077059,7.7]}
          scale={0.289452}
        />
        <group
          name="Spring001"
          position={[6.703304, 0.288906, 3.689106]}
          rotation={[1.35263, 0, -Math.PI / 2]}
          scale={0.015127}
        >
          <mesh
            name="Circle012"
            castShadow
            receiveShadow
            geometry={nodes.Circle012.geometry}
            material={materials["Black.002"]}
          />
          <mesh
            name="Circle012_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle012_1.geometry}
            material={materials["Light_black.002"]}
          />
        </group>
        <group
          name="Bateria_luz001"
          position={[-1.506137, 9.575981, -5.539279]}
          scale={0.186784}
        >
          <mesh
            name="Cube021"
            castShadow
            receiveShadow
            geometry={nodes.Cube021.geometry}
            material={glowBlue}
          />
          <mesh
            name="Cube021_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube021_1.geometry}
            material={materials["Material.023"]}
          />
        </group>
        <group
          name="Rear_wheel"
          position={[5.704612, 0.292098, 2.534173]}
          rotation={[-Math.PI / 2, -0.983063, Math.PI]}
          scale={[0.297371, 0.159821, 0.297371]}
        >
          <mesh
            name="Cylinder012"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012.geometry}
            material={materials["Black.002"]}
          />
          <mesh
            name="Cylinder012_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012_1.geometry}
            material={materials["Light_black.002"]}
          />
        </group>
        <mesh
          name="SILLA"
          castShadow
          receiveShadow
          geometry={nodes.SILLA.geometry}
          material={materials.sillaDormir}
          position={[-0.037715, 6.521499, -1.199734]}
          rotation={[-Math.PI, 1.343114, -Math.PI]}
          scale={[0.714393, 0.714392, 0.714393]}
        />
        <group
          name="carro_garage"
          position={[-2.247081, 0.283671, 3.973172]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.03076}
        >
          <mesh
            name="Mesh124"
            castShadow
            receiveShadow
            geometry={nodes.Mesh124.geometry}
            material={materials["Material.015"]}
          />
          <mesh
            name="Mesh124_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh124_1.geometry}
            material={materials.llanta}
          />
          <mesh
            name="Mesh124_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh124_2.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            name="Mesh124_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh124_3.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            name="Mesh124_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh124_4.geometry}
            material={materials["luces delasnteras"]}
          />
          <mesh
            name="Mesh124_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh124_5.geometry}
            material={materials["Material.034"]}
          />
        </group>
        <group
          name="Matera_parqu"
          position={[-4.464219, 0.135409, 6.514155]}
          rotation={[1.656082, 0.071773, 0.850091]}
          scale={[0.012395, 0.012498, 0.020809]}
        >
          <mesh
            name="Mesh004"
            castShadow
            receiveShadow
            geometry={nodes.Mesh004.geometry}
            material={materials.lambert18}
          />
          <mesh
            name="Mesh004_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh004_1.geometry}
            material={materials.marmol}
          />
          <mesh
            name="Mesh004_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh004_2.geometry}
            material={materials.TIERRA}
          />
        </group>
        <mesh
          name="lampara"
          castShadow
          receiveShadow
          geometry={nodes.lampara.geometry}
          material={materials.marmol}
          position={[-1.82792, 2.146587, 2.305249]}
          scale={[0.113191, 0.051728, 0.051728]}
        />
        <mesh
          name="lampara002"
          castShadow
          receiveShadow
          geometry={nodes.lampara002.geometry}
          material={materials.marmol}
          position={[-0.79562, 8.400322, -2.262463]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.113191, 0.051728, 0.051728]}
        />
        <group
          name="Spring002"
          position={[7.236587, 0.283898, 3.694696]}
          rotation={[1.771509, 0, Math.PI / 2]}
          scale={0.015127}
        >
          <mesh
            name="Circle011"
            castShadow
            receiveShadow
            geometry={nodes.Circle011.geometry}
            material={materials["Black.002"]}
          />
          <mesh
            name="Circle011_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle011_1.geometry}
            material={materials["Light_black.002"]}
          />
        </group>
        <group
          name="carro_taz"
          position={[3.850041, 0.031522, 5.371466]}
          rotation={[Math.PI / 2, 0, -0.812481]}
          scale={0.305806}
        >
          <mesh
            name="Mesh126"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126.geometry}
            material={materials["aiStandardSurface1.001"]}
          />
          <mesh
            name="Mesh126_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_1.geometry}
            material={materials.bombper}
          />
          <mesh
            name="Mesh126_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_2.geometry}
            material={materials.taxi}
          />
          <mesh
            name="Mesh126_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_3.geometry}
            material={glowBlue}
          />
          <mesh
            name="Mesh126_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_4.geometry}
            material={materials.luces}
          />
          <mesh
            name="Mesh126_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_5.geometry}
            material={materials.llanta}
          />
          <mesh
            name="Mesh126_6"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_6.geometry}
            material={materials["Material.014"]}
          />
        </group>
        <mesh
          name="CERCA"
          castShadow
          receiveShadow
          geometry={nodes.CERCA.geometry}
          material={materials["Material.016"]}
          position={[4.841491, 0.160302, -4.54964]}
          scale={[0.023458, 0.056788, 0.084373]}
        />
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials["Material.022"]}
          position={[-1.568122, -0.270236, -1.704771]}
          scale={70.621643}
        />
        <group
          name="Rear_wheel001"
          position={[5.704612, 0.292098, 3.893819]}
          rotation={[Math.PI / 2, 1.014799, Math.PI]}
          scale={[0.297371, 0.159821, 0.297371]}
        >
          <mesh
            name="Cylinder011"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder011.geometry}
            material={materials["Black.002"]}
          />
          <mesh
            name="Cylinder011_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder011_1.geometry}
            material={materials["Light_black.002"]}
          />
        </group>
        <group
          name="Front_wheel001"
          position={[7.237894, 0.265115, 3.900845]}
          rotation={[-Math.PI / 2, 1.307543, 0.000001]}
          scale={[0.270337, 0.145775, 0.270337]}
        >
          <mesh
            name="Cylinder021"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder021.geometry}
            material={materials["Black.002"]}
          />
          <mesh
            name="Cylinder021_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder021_1.geometry}
            material={materials["Light_black.002"]}
          />
        </group>
        <group
          name="Front_wheel"
          position={[7.237894, 0.265115, 2.52715]}
          rotation={[Math.PI / 2, -1.402616, 0]}
          scale={[0.270337, 0.145775, 0.270337]}
        >
          <mesh
            name="Cylinder022"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder022.geometry}
            material={materials["Black.002"]}
          />
          <mesh
            name="Cylinder022_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder022_1.geometry}
            material={materials["Light_black.002"]}
          />
        </group>
        <group
          name="CarroCamper"
          position={[6.398108, 0.215089, 3.213997]}
          rotation={[0.004201, 0, 0]}
          scale={[1.618906, 0.269818, 0.539635]}
        >
          <mesh
            name="Cube009"
            castShadow
            receiveShadow
            geometry={nodes.Cube009.geometry}
            material={materials["Black.002"]}
          />
          <mesh
            name="Cube009_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_1.geometry}
            material={materials["Light_black.002"]}
          />
          <mesh
            name="Cube009_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_2.geometry}
            material={materials["Orange.002"]}
          />
          <mesh
            name="Cube009_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_3.geometry}
            material={materials["Glass.002"]}
          />
          <mesh
            name="Cube009_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_4.geometry}
            material={glowYellow}
          />
          <mesh
            name="Cube009_5"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_5.geometry}
            material={materials["Light_red.002"]}
          />
          <mesh
            name="Cube009_6"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_6.geometry}
            material={materials["Dark_brown.002"]}
          />
          <mesh
            name="Cube009_7"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_7.geometry}
            material={materials["Dark_brown_handle.002"]}
          />
          <mesh
            name="Cube009_8"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_8.geometry}
            material={materials["Glass_trailer.002"]}
          />
          <mesh
            name="Cube009_9"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_9.geometry}
            material={materials["Brown.002"]}
          />
        </group>
        <mesh
          name="ladrillo"
          castShadow
          receiveShadow
          geometry={nodes.ladrillo.geometry}
          material={materials.ladrillos}
          position={[-4.666406, 2.539444, 5.726112]}
          scale={[0.234582, 0.095865, 0.05733]}
        />
        <mesh
          name="Farol"
          castShadow
          receiveShadow
          geometry={nodes.Farol.geometry}
          material={materials.farol}
          position={[8.293884, -0.003551, 7.704031]}
          scale={[0.314585, 0.152046, 0.314585]}
          rotation={[0,-Math.PI/2,0]}
          material-color={"#727272"}
        />
        <group
          name="mesa3"
          position={[0.543932, 6.468303, -1.446284]}
          scale={[0.271695, 0.05171, 0.271695]}
        >
          <mesh
            name="Cube006"
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials.marmol}
          />
          <mesh
            name="Cube006_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials["PATA MESA"]}
          />
        </group>
        <mesh
          name="lamparaCalle"
          castShadow
          receiveShadow
          geometry={nodes.lamparaCalle.geometry}
          material={glowBlue}
          position={[7.55, 3.077059, 7.75]}
          scale={0.289452}
        />
        <mesh
          name="lampara001"
          castShadow
          receiveShadow
          geometry={nodes.lampara001.geometry}
          material={materials.marmol}
          position={[-1.82792, 2.146587, 5.296983]}
          scale={[0.113191, 0.051728, 0.051728]}
        />
        <mesh
          name="lampara003"
          castShadow
          receiveShadow
          geometry={nodes.lampara003.geometry}
          material={materials.marmol}
          position={[-2.708237, 8.400322, -2.253526]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.113191, 0.051728, 0.051728]}
        />
        <group
          name="LAMPRAPARASOL"
          position={[-2.775614, 8.85701, -0.069946]}
          scale={0.072965}
        >
          <mesh
            name="Sphere002"
            castShadow
            receiveShadow
            geometry={nodes.Sphere002.geometry}
            material={glowRedyell}
          />
          <mesh
            name="Sphere002_1"
            castShadow
            receiveShadow
            geometry={nodes.Sphere002_1.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          name="LAMPRAPARASOL001"
          position={[-3.468706, 8.858953, -0.745617]}
          scale={0.072965}
        >
          <mesh
            name="Sphere003"
            castShadow
            receiveShadow
            geometry={nodes.Sphere003.geometry}
            material={glowRedyell}
          />
          <mesh
            name="Sphere003_1"
            castShadow
            receiveShadow
            geometry={nodes.Sphere003_1.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group
          name="carf4"
          position={[8.382282, 0.956544, 7.7425]}
          scale={[0.013818, 0.155087, 0.362441]}
          rotation={[0,-Math.PI/2,0]}
          onClick={()=>{
            dispatch(chCam());
            
          }}
        
        >
          <mesh
            name="Cube"
            castShadow
            receiveShadow
            geometry={nodes.Cube.geometry}
            material={materials.farol}
          />
          <mesh
            name="Cube_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={glowYellow}
          >
          <Html scale={1} rotation={[0, Math.PI/2, 0]} position={[3, 0, -0.1]} transform occlude>
          <div className="annotation" style={{ position:"relative",fontSize: '0.9em',height:"50px",width:"75px", textAlign:"center", top:"-10px"}} onClick={()=>{ dispatch(chCam());}}>
             <p style={{position:"relative", textAlign:"center", top:"15px"}}>Projects</p> 
          </div>
        </Html>
          </mesh>
        </group>
        <group
          name="carF"
          position={[8.382282, 2.280551, 7.8425]}
          rotation={[-Math.PI, Math.PI/2, 0]}
          scale={[0.013818, 0.155087, 0.362441]}
          onClick={()=>{
           
            dispatch(chTravel());

                          }}
          
        >
          <mesh
            name="Cube002"
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials.farol}
          />
          <mesh
            name="Cube002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={glowBuesCar}
          >
            <Html scale={1} rotation={[0, Math.PI/2, Math.PI]} position={[3, 0, -0.1]} transform occlude >
          <div className="annotation2"  style={{ position:"relative", fontSize: '0.9em',cursor:"pointer",height:"50px",width:"75px",}} onClick={()=>{dispatch(chTravel())}}>
          <p style={{position:"relative", textAlign:"center", top:"9px"}}>About Me</p>
          </div>
        </Html>
          </mesh>
        </group>
        <group
          name="carF3"
          position={[8.382282, 1.380396, 7.8425]}
          rotation={[-Math.PI, Math.PI/2, 0]}
          scale={[0.013818, 0.155087, 0.362441]}
          
        >
          <mesh
            name="Cube003"
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials.farol}
          />
          <mesh
            name="Cube003_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube003_1.geometry}
            material={glowGreen}
          >
            
          </mesh>
        </group>
        <group
          name="carF2"
          position={[8.382282, 1.80931, 7.757678]}
          rotation={[-Math.PI, Math.PI/2, 0]}
          scale={[0.013818, 0.236918, 0.2659]}
          onClick={()=>{
           
           dispatch(chBuzon())
           

                         }}
        >
          <mesh
            name="Cube004"
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials.farol}
          />
          <mesh
            name="Cube004_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube004_1.geometry}
            material={glowPurpue}
          >
            <Html scale={1} rotation={[0, Math.PI/2, Math.PI]} position={[3, 0, -0.1]} transform occlude>
            <img src="/barcode.png" style={{position:"relative", width:"60px", left: "5px", top:"5px",cursor:"pointer"}} onClick={()=>{dispatch(chBuzon())}}></img>
          <div className="annotation2"  style={{position:"relative", fontSize: '0.9em', top:"-10px", cursor:"pointer"}} onClick={()=>{dispatch(chBuzon())}}>
             Erwin <span className="letter" style={{ fontSize: '1em', color: "#FFFFFF", pointerEvents : "none" }} ></span>
          </div>
        </Html>
          </mesh>
        </group>
        <group
          name="Bateria_luz002"
          position={[-2.053834, 9.575981, -5.539279]}
          scale={0.186784}
        >
          <mesh
            name="Cube005"
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={glowBlue}
          />
          <mesh
            name="Cube005_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials["Material.023"]}
          />
        </group>
        <mesh
          name="SILLA001"
          castShadow
          receiveShadow
          geometry={nodes.SILLA001.geometry}
          material={materials.sillaDormir}
          position={[1.879279, 6.492455, -1.088489]}
          rotation={[0, 1.382139, 0]}
          scale={0.714392}
        />
        <group
          name="machine_ven"
          position={[-1.348886, 1.367616, 0.563796]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.52234, 1.011083, 0.341664]}
        >
          <mesh
            name="Cube028"
            castShadow
            receiveShadow
            geometry={nodes.Cube028.geometry}
            material={materials.cubierta_maqui}
          />
          <mesh
            name="Cube028_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube028_1.geometry}
            material={materials.salen_botte}
          />
          <mesh
            name="Cube028_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube028_2.geometry}
            material={materials.marco_machine}
          />
          
          
        </group>
        <mesh
        position={[-0.97, 1.715, 0.563796]}
        geometry={new THREE.PlaneGeometry(1,1)}
        rotation={[0,Math.PI/2,0]}
        material={new THREE.MeshBasicMaterial({
            map: VideoTextures
                    })}
        >
        {
          proyect ? <Html scale={0.049} position={[0.499, -0.53,0]} transform occlude>
          <div className="annotation4">
              <div className="BackProyec" id="BackProyec" style={{ fontSize: '4.5em'}} onClick={()=>{dispatch(chCam2())}}  onPointerOver={() => {setHovered(true)}}
              onPointerOut={() => setHovered(false)}>
                Go Back <span className="letter" style={{ fontSize: '1.5em', color: "#FFFFFF" }} ></span>
              </div>
                <Proyects/>
              </div>
             
          </Html>:<></> 
          
        }


        </mesh>
        <mesh
          name="Mailbox001"
          castShadow
          receiveShadow
          geometry={nodes.Mailbox001.geometry}
          material={materials.Mailbox}
          position={[8.566858, 0, 0.825209]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[1.623191, 1.059236, 0.925181]}
        />
        <mesh
          name="planta_b001"
          castShadow
          receiveShadow
          geometry={nodes.planta_b001.geometry}
          material={materials.materaLinda}
          position={[-1.286871, 6.586444, 1.302448]}
          rotation={[0, -0.1602, 0]}
          scale={0.014893}
        />
        <mesh
          name="planta_b"
          castShadow
          receiveShadow
          geometry={nodes.planta_b.geometry}
          material={materials.materaLinda}
          position={[1.661881, 0.508187, -1.959844]}
          rotation={[0, 1.410597, 0]}
          scale={0.014893}
        />
        <mesh
          name="planta_b002"
          castShadow
          receiveShadow
          geometry={nodes.planta_b002.geometry}
          material={materials.materaLinda}
          position={[1.726622, 3.444114, -1.924667]}
          rotation={[0, 1.410597, 0]}
          scale={0.014893}
        />
        <mesh
          name="planta_b003"
          castShadow
          receiveShadow
          geometry={nodes.planta_b003.geometry}
          material={materials.materaLinda}
          position={[-5.157186, 6.594273, -1.741478]}
          rotation={[0, 1.410597, 0]}
          scale={0.014893}
        />
        <mesh
          name="matera_b002"
          castShadow
          receiveShadow
          geometry={nodes.matera_b002.geometry}
          material={materials["Material.012"]}
          position={[1.646543, 0.404498, -1.933686]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.25066, 0.216994, 0.25066]}
        />
        <group
          name="matera_b003"
          position={[-1.313028, 6.482755, 1.28711]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.25066, 0.216994, 0.25066]}
        >
          <mesh
            name="Cube073"
            castShadow
            receiveShadow
            geometry={nodes.Cube073.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            name="Cube073_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube073_1.geometry}
            material={materials["Material.013"]}
          />
        </group>
        <mesh
          name="matera_b"
          castShadow
          receiveShadow
          geometry={nodes.matera_b.geometry}
          material={materials["Material.013"]}
          position={[1.711284, 3.340425, -1.89851]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.25066, 0.216994, 0.25066]}
        />
        <mesh
          name="matera_b001"
          castShadow
          receiveShadow
          geometry={nodes.matera_b001.geometry}
          material={materials["Material.013"]}
          position={[-5.172524, 6.490584, -1.71532]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={[0.25066, 0.216994, 0.25066]}
        />
        
       
      <Text3D  curveSegments={32}
          bevelEnabled
          bevelSize={0.04}
          bevelThickness={0.1}
          height={0.5}
          lineHeight={0.5}
          letterSpacing={-0.06}
          size={1.5}
          font="/Inter_Bold.json"
      position={[10,10,0]}
      rotation={[-Math.PI/2,-Math.PI/2,-Math.PI/2]}
      >
          {buzon? `Erwin Soto`:''}
          <meshStandardMaterial color="white" />
        </Text3D>

        <Text3D letterSpacing={-0.06} size={1} font="/Inter_Bold.json"
      position={[10,8.5,0]}
      rotation={[-Math.PI/2,-Math.PI/2,-Math.PI/2]}
      lineHeight={0.7}
      >
          {buzon? 'Data scientist\nDeveloper\nDBA':''}
          <meshStandardMaterial color="white" />
        </Text3D>

        <Text3D letterSpacing={-0.06} size={1} font="/Inter_Bold.json"
      position={[10,2.5,0]}
      rotation={[-Math.PI/2,-Math.PI/2,-Math.PI/2]}
      lineHeight={0.6}
      onPointerOver={() => {setColor("red")}}
      onPointerOut={() => setColor("white")} 
      onClick={()=>{dispatch (chBuzon2())}}
      >
          {buzon ?'<-Back' :''}
          <meshStandardMaterial color={color} />
        </Text3D>


      </group>
    </group>
  );
}


useGLTF.preload("/casaPort27.glb");
