/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Room2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/carro.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="carro_taz"
          position={[3.85, 0.03, 5.37]}
          rotation={[Math.PI / 2, 0, -0.81]}
          scale={0.31}
        >
          <mesh
            name="Mesh126"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126.geometry}
            material={materials["aiStandardSurface1.001"]}
          />
          <mesh
            name="Mesh126_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_1.geometry}
            material={materials.bombper}
          />
          <mesh
            name="Mesh126_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_2.geometry}
            material={materials.taxi}
          />
          <mesh
            name="Mesh126_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_3.geometry}
            material={materials.luces_delatenras}
          />
          <mesh
            name="Mesh126_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_4.geometry}
            material={materials.luces}
          />
          <mesh
            name="Mesh126_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_5.geometry}
            material={materials.llanta}
          />
          <mesh
            name="Mesh126_6"
            castShadow
            receiveShadow
            geometry={nodes.Mesh126_6.geometry}
            material={materials["Material.014"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/carro.glb");
